### ISSUE TITLE
No hardcode in tests

### ISSUE THREAD

**Issue by gwi-nfq** [agnfq/lab1#11]
https://github.com/agnfq/lab1/blob/1d240d399847df75b329a275b7eefe7d78535062/tests/ApiTest.php#L13

Arrange, Act and Assert. Prepare dynamic data. Not the hardcoded one.

**Comment by agnfq** [comment]
And actually a token is not needed to display products. list, this has been removed.

**Comment by gwi-nfq** [comment]
https://github.com/agnfq/lab1/blob/1d240d399847df75b329a275b7eefe7d78535062/tests/ApiTest.php#L22

Great. Another thing is to mock the API call. Don't actually call it. 

Take a look at this from Symfony Documentation.

https://symfony.com/doc/current/testing.html#application-tests
