### ISSUE TITLE
Refactor AuthController

### ISSUE THREAD

**Issue by gwi-nfq** [agnfq/lab1#4]
https://github.com/agnfq/lab1/blob/1d240d399847df75b329a275b7eefe7d78535062/src/Controller/AuthController.php#L52-L74

These methods are not related to AuthController. Please refactor this.

**Comment by agnfq** [comment]
Sadly, Symfony requires me to implement interface UserInterface to access its security libraries, so I must stub these methods

**Comment by gwi-nfq** [comment]
> Sadly, Symfony requires me to implement interface UserInterface to access its security libraries, so I must stub these methods

Alright. Let refactor this snippet and we are good to go.

https://github.com/agnfq/lab1/blob/1d240d399847df75b329a275b7eefe7d78535062/src/Controller/AuthController.php#L31-L41
