### ISSUE TITLE
Route Validation

### ISSUE THREAD

**Issue by gwi-nfq** [agnfq/lab1#8]
https://github.com/agnfq/lab1/blob/1d240d399847df75b329a275b7eefe7d78535062/src/Controller/OrderController.php#L59

Use Route validation and input validation for this use case. You don't have to manually check whether if product_id and quantity are in the request.

https://symfony.com/doc/current/routing.html#parameters-validation

**Comment by agnfq** [comment]
Basic error validation added to ProductService
