### ISSUE TITLE
Refactor ProductController

### ISSUE THREAD

**Issue by gwi-nfq** [agnfq/lab1#9]
https://github.com/agnfq/lab1/blob/1d240d399847df75b329a275b7eefe7d78535062/src/Controller/ProductController.php#L14

Same comment as other controllers

**Comment by agnfq** [comment]
Product manipulation methods moved from ProductController to ProductRepository, unused ProductController removed from project.

**Comment by gwi-nfq** [comment]
Repository aren't suppose to accept HTTP Requests.

https://martinfowler.com/eaaCatalog/repository.html

https://martinfowler.com/eaaCatalog/serviceLayer.html

**Comment by agnfq** [comment]
Completely refactored ProductController logic; created service and repository; split out functions
